### PR TITLE
Add license info to all package.json

### LINKED ISSUE #752: Add licences to package.json
Hi,

Would it be possible to fill in the licence field in [package.json](https://docs.npmjs.com/files/package.json#license) for each package.json in the monorepo? This makes it easier to verify in an automated way.

Thanks!

### PR DESCRIPTION
**Pull request by mlucool**
This does NOT change the license of this project, just makes it
easier to automate finding.

Fixes #752

### CODE REVIEW

**Comment by taye** [comment]
Thanks!

**Comment by mlucool** [comment]
@taye it seems a few new packages are missing licences

**Comment by taye** [comment]
I checked version 1.8.1 and they all seem to be there.

**Comment by taye** [comment]
Oh sorry, one is missing in the package.json

**Comment by taye** [comment]
Fixed in 1.8.2. Thanks for the heads up.

**Comment by mlucool** [comment]
Thanks for the quick fix!

**Pull request merged**
