### PR TITLE
Add snap.targets and snap.relativePoints reference to snap modifier

### PR DESCRIPTION
**Pull request by Hufschmidt**
### Description

This PR adds an additional property to the `InteractEvent.snap` property, namely:

````
InteractEvent.snap.ref = {
  reference: ...,
  target: ...
}
````

Where reference contains the **closest** matching reference-point, via its **index** in [`relativePoints`](http://interactjs.io/docs/snapping/#relativepoints).
While target contains the **closest** matching snap-target, via its **index** in [`targets`](http://interactjs.io/docs/snapping/#targets).

### Use case

Currently it is quite difficult to detect which snap-target (anchor) an interact.js-draggable was snapped to and via which relative-point, because `InteractEvent.snap.x` and `InteractEvent.snap.y` contain target-points after beeing shifted by the closest relative-point.

This should allow users to skip having to redo calculations in `src/modifiers/snap.js` simply to get this information. :smile_cat:

### CODE REVIEW

**Comment by taye** [comment]
A syntax error at https://github.com/Hufschmidt/interact.js/blob/82659ac/src/modifiers/snap.js#L99 breaks `npm run gulp build` process and using `Object.keys(...).forEach` doesn't have the same result as the `for ... of` statements that were replaced.

I would prefer to change the closest object to something like:

```javascript
closest.x = target.x;
closest.y = target.y;
closest.target = originalTarget;
closest.relativePoint = originalRelativePoint;
closest.targetIndex... closest.relativePointIndex...
```

**Comment by Hufschmidt** [comment]
My bad, I first reverse-engineered the overall code-flow of interact.js using the distribution version dist/intertact.js because following the code was easier.
Only after hacking my changes into the dist version I moved/reimplemented it in the real source-code but skipped actual testing due to limited time. :monkey_face:

I rewrote the implementation using your suggestions and made sure its building and working correctly. :smile:

For some reason I'm unable to to get gulp test to run successfully though, is there more required then:
```
npm install
bower install
gulp build
gulp test

```
Karma fails with `Uncaught TypeError: interact(...).draggable is not a function`

**Comment by Hufschmidt** [comment]
## Documentation

This PR now adds the following properties:

* `InteractEvent.snap.target` - Clostest unmodified point set via _draggable({snap.targets})_ or returned by a target-function set via _draggable({snap.targets})_
* `InteractEvent.snap.targetIndex` - Index of point or function in targets-array set via _draggable({snap.targets})_
* `InteractEvent.snap.relativePoint` - Position of closest point on the triggering interactable object (relative to its [css-given anchor](http://www.w3schools.com/css/css_positioning.asp))
* `InteractEvent.snap.relativePointIndex` - Index of closest point in the triggering interactable object as set via draggable({snap.relativePoints})

**Comment by taye** [comment]
>For some reason though I'm unable to to get gulp test to run successfully (even on master), is there more required then:

I wrote new tests that actually work some time after you created this branch. Merging with the current master branch should bring in the new tests. The command to run the tests after installing the new dependencies is `npm test`.

**Comment by Hufschmidt** [comment]
Cool sweet, I rebased my PR onto latest master, now build and test run successfully without warnings/errors. Should be ready for a final review iff you decide to merge.

**Comment by taye** [comment]
https://github.com/taye/interact.js/pull/452/files#r95083665

**Pull request closed without merging**
