### PR TITLE
Added custom corner resizing

### PR DESCRIPTION
**Pull request by Nic128**
When defining custom resizeEdges, we don't have access to customize the corner elements. This optionally enables it.

### CODE REVIEW

**Comment by eazuka** [comment]
hi @taye any hope of this pull request being merge?
thanks for this very nice js tool.

**Comment by taye** [comment]
A corner is made of two edges.

**Comment by taye** [comment]
In that case, use only four handles which match two adjacent edges each. Then all handles are corners and there are no single axis edges. With your PR, the control is nearly identical but there's a lot more duplication in the code.

**Comment by Nic128** [comment]
Could you make an example for the users then? It seems to be a recurring question.

**Comment by ubbcou** [comment]
> e

I'm sorry, but can you give me an example. Thank you. :D

**Comment by ubbcou** [comment]
> In that case, use only four handles which match two adjacent edges each. Then all handles are corners and there are no single axis edges. With your PR, the control is nearly identical but there's a lot more duplication in the code.

I'm sorry, but can you give me an example. Thank you. :D

**Comment by ubbcou** [comment]
> > In that case, use only four handles which match two adjacent edges each. Then all handles are corners and there are no single axis edges. With your PR, the control is nearly identical but there's a lot more duplication in the code.
> 
> I'm sorry, but can you give me an example. Thank you. :D

Result: [Corner Resizing](https://codesandbox.io/s/interact-js-corner-resize-1ghlu?file=/index.html)

Hopefully it will help others as well~😀

**Pull request closed without merging**
