### PR TITLE
Optionally limit horizontal, vertical autoScroll

### PR DESCRIPTION
**Pull request by 73rhodes**
Suggestion to add the ability to optionally confine autoScroll in the horizontal or vertical direction.

### CODE REVIEW

**Comment by taye** [comment]
I would think it better to change the `speed` option to `velocityX` and `velocityY` so that a `0` value would disable autoScroll in that axis. The `autoScroll` method could be kept backwards compatible simply by using the given speed (if any) as the values for `velocityX/Y`.

**Comment by 73rhodes** [comment]
Good call, let me try that.

**Comment by 73rhodes** [comment]
How would you deal with `autoScroll.speed = options.speed` ?

**Comment by taye** [comment]
I'm not sure what you mean. When/how would that happen?

**Comment by 73rhodes** [comment]
That line is within the autoScrollMove function. The speed property is passed on this way, and velocityX / velocityY don't translate easily into a single speed property. This is why simple flags to disable horizontal or vertical scrolling appeared to be the simplest progressive enhancement...

**Comment by taye** [comment]
That line is actually obsolete. [Around line 189](https://github.com/73rhodes/interact.js/blob/50232a1/interact.js#L191) is where changes need to be made to something like this:

```javascript
var dtx = (now - autoScroll.prevTimeX) / 1000,
    dty = (now - autoScroll.prevTimeY) / 1000,
    vx, vy, sx, sy;

// velocity: { x: pxPerS, y: pxPerS }
if (options.velocity) {
    vx = options.velcoity.x;
    vy = options.velcoity.y;
}
else {
    vx = vy = options.speed;
}

sx = vx * dt;
sy = vy * dt;
...
```

Perfect backwards compatibility can be maintained. I think that having different X and Y velocities for scroll could be useful but I'm not sure. The only use case that I can think of is extending the current autoScroll so that the scroll velocity depends on the distance to the container edge.

**Comment by 73rhodes** [comment]
Thanks for the suggestion. Implemented and tested; works great!

**Comment by pumpknhd** [comment]
@taye Does the Velocity option still work? I seem to be unable to restrict the auto-scroll to just the Y axis. Thank you.

**Pull request merged**
