### PR TITLE
Update interact.js

### PR DESCRIPTION
**Pull request by baptistebriel**
fixed issue #277 & #278 
do not add depreciated props like webkitMovementY & webkitMovementX

### CODE REVIEW

**Comment by taye** [comment]
Checking for those property names whenever the extend function is being used on any object wasn't a good solution. I created and used a new pointerExtend function instead.

**Comment by baptistebriel** [comment]
Yes, that's definitely cleaner. Thanks! 👍

**Comment by taye** [comment]
:heart:

**Comment by baptistebriel** [comment]
Okay, so now I get even more warnings. :)

Here's the `pointerExtend` function updated with the new depreciated props.

```javascript
function pointerExtend (dest, source) {
        for (var prop in source) {
            if (prop !== 'webkitMovementX' && prop !== 'webkitMovementY' && prop !== 'webkitRadiusX' && prop !== 'webkitRadiusY' && prop !== 'webkitRotationAngle' && prop !== 'webkitForce'){
                dest[prop] = source[prop];
            }
        }
        return dest;
}
```

Looks like `webkit` is currently dropping all the prefixed props, but I'm not sure..
In that case we could do something like:

```javascript
function pointerExtend (dest, source) {
        for (var prop in source) {
            if (prop.indexOf('webkit') == -1){
                dest[prop] = source[prop];
            }
        }
        return dest;
}
```

Also, could you update the version on npm too? Thanks!

**Comment by taye** [comment]
Thanks for the update. `if (prop.indexOf('webkit') == -1){` would also prevent people using any new prefixed properies that haven't been deprecated. We could use a more specific and concise RegExp like `/^webkit(Movement[XY]|Radius[XY]|RotationAngle)$/` but simple `===` comparison is much faster so I think I'll go with that. Actually we could combine the two and use the RegExp only if the string starts with "webkit".

I plan on releasing by the end of the week. You can use the master version with npm now if you use `"interact.js": "taye/interact.js#master"` as a dependency in your package.json file.

**Comment by baptistebriel** [comment]
Cool! Perfect, thanks @taye 👍

**Pull request closed without merging**
