### PR TITLE
domUtils.ts: fix NPE in indexOfDeepestElement if first element has no parent

### PR DESCRIPTION
**Pull request by BacLuc**
This happened with a large svg document with lot's of draggable elements and dropzones.

### CODE REVIEW

**Comment by taye** [comment]
Thank you!

The build errors should be fixed after merging master again.

Because I'm planning on selling a [pro](interactjs.io/pro/) version with a commercial license, I have to ask if you would be okay with me re-licensing your code. It would still remain MIT licensed on github and npm.

**Comment by taye** [comment]
Great. Please fill out this template and post it as a comment:

```markdown
I, {{{contributor name}}}, give @taye permission to license my contributions on
any terms they like.  I am giving them this license in order to make it
possible for them to accept my contributions into their project.

***As far as the law allows, my contributions come as is, without any warranty
or condition, and I will not be liable to anyone for any damages related to
this software or this license, under any kind of legal claim.***
```

**Comment by BacLuc** [comment]
I, @BacLuc , give @taye permission to license my contributions on
any terms they like.  I am giving them this license in order to make it
possible for them to accept my contributions into their project.

***As far as the law allows, my contributions come as is, without any warranty
or condition, and I will not be liable to anyone for any damages related to
this software or this license, under any kind of legal claim.***

**Comment by taye** [comment]
Thanks a bunch and sorry for the formality.

**Comment by taye** [comment]
`v1.10.4` is released.

**Pull request merged**
