### PR TITLE
Modularize the codebase and use ES6 features with Babel+browserify+gulp build

### LINKED ISSUE #110: Improving Code Quality / Approachability
I really like this library, however it's just 1 file and well over 5000 lines long. Do you have plans to break things up into Common JS modules, add JSDoc comments and code quality tools?

It'd be really nice also there were natural hooks for other frameworks and libraries (i.e custom mixin for React or Angular module).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/6418460-improving-code-quality-approachability?utm_campaign=plugin&utm_content=tracker%2F518286&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F518286&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by taye**
This branch splits the monolithic `./interact.js` file into separate modules to be bundled together with [browserify](http://browserify.org/). It also makes actions (drag, resize, gesture), modifiers (snap, restrict), pointerEvents (`down`, `tap`, `hold`, etc.) and autoScroll optional and provides interfaces for adding new actions and modifiers.

An internal `signals` API been introduced which allows modules to hook into various points in the codebase without tight coupling, eg.:

```javascript
signals.on('interactable-new', function (arg) { ... });

// in Interactable constructor
signals.fire('interactable-new', {
    interactable: this,
    element: element,
    options: options,
    win: _window
});
```

Eslint is now used for style checking instead of JSHint and the formatting style of the project has been changed. Most notably:

 - 2-space indentation instead of 4
 - the use of various ES6 features (see .babelrc)
 - `let` and `const` instead of `var`
 - only one `let`/`const` per identifier
 - multi-line trailing commas

**One-time setup:**

 - install [Node.js](https://nodejs.org/) if you don't have it
 - clone the interact.js repository
 - enter the directory into which it was cloned
 - on the command line, run `npm install` to install interact.js' development dependencies

**To build interact.js, run:**

```shell
npm run build
```

This will generate the following files in the `./dist` directory:

    interact.js
    interact.js.map
    interact.min.js
    interact.min.js.map

Many thanks to @stephen-james for his help!

Closes #110

### CODE REVIEW

**Comment by stephen-james** [comment]
:) :+1:

**Comment by stbaer** [comment]
:+1:  this looks good. 

How stable is the modularization branch / already usable?

**Comment by tedvanderveen** [comment]
Great work! This will take this lib to the next level. Did you consider move to Typescript modules/namespace system?

**Comment by taye** [comment]
@stbaer It seems fairly stable when I've used it. I've also corrected a few issues that exist in the master branch. Snapping, restricting and inertia might have some problems or behave *a little* differently. Excluding things like actions and modifiers can be done by stubbing the file out with browserify's `ignore` setting. The plan is to have an entry file which can be easily edited to include/exclude submodules.

@tedvanderveen I didn't really consider switching to Typescript and I was sort of planning on switching to ES6 in the near future. What advantages would Typescript provide over ES6 and can it be used with browserify hassle-free?

**Comment by stbaer** [comment]
@taye What is your opinion on using external dependencies?

One great advantage of browserify is that it allows you to require installed npm dependencies directly.

Just as an example, utils/extend could easily be replaced by [object-assign](https://www.npmjs.com/package/object-assign).

**Comment by tedvanderveen** [comment]
@taye Typescript allows us to use ES6 (and some ES7 stuff) now and compile down to ES5 using CommonJs modules (that can be used by Browserify yes). More module output introduced recently: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-umd-and-system-module-output

**Comment by NSinopoli** [comment]
:+1: Great work!

**Comment by taye** [comment]
@stbaer If they fit very well, I'd be happy to use them. `Object.assign` isn't suitable though as it only works for `ownEnumerableKeys` and so they can't copy event properties as they are essentially [all on the event prototype](https://bugzilla.mozilla.org/show_bug.cgi?id=1018605). Also that polyfill is a bit more complex than is needed for the way `extend` is currently used.

@tedvanderveen Typescript seems good but I'd prefer to go with just Babel or Traceur *maybe* as a step towards using Typescript eventually.

**Pull request merged**
